name:                pandoc-symreg
version:             0.2.1.3
synopsis:            A tool to convert symbolic regression expressions into different formats.
github:              "folivetti/pandoc-symreg"
license:             GPL-3
author:              "Fabricio Olivetti de França"
maintainer:          "fabricio.olivetti@gmail.com"
copyright:           "2023 Fabricio Olivetti de França"
category:            Text, Math

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A pandoc-like cli tool and library to convert symbolic regression expressions to convenient formats
# category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A pandoc-like cli tool and library to convert symbolic regression expressions to convenient formats

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11 && < 0.12
- attoparsec >= 0.14 && < 0.15
- attoparsec-expr >= 0.1 && < 0.2
- optparse-applicative >= 0.18 && < 0.19
- mtl >= 2.2 && < 2.4
- srtree >= 1.0.0.4 && < 1.1
  #- hegg >= 0.5 && < 0.6
- containers >= 0.6.5 && < 0.7
- deriving-compat >= 0.6.3 && < 0.7
- ieee754 >= 0.8.0 && < 0.9
- transformers >= 0.6
- text >= 2
- graphviz

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-do-bind

library:
  source-dirs: src

executables:
  pandoc-symreg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - pandoc-symreg

tests:
  pandoc-symreg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-symreg
